const SET_FILE = "SET_FILE";
const SET_UPLOADED_FILE = "SET_UPLOADED_FILE";
const SET_UPLOADED_FILES = "SET_UPLOADED_FILES";
const ADD_UPLOADED_FILE = "ADD_UPLOADED_FILE";

export { SET_FILE, SET_UPLOADED_FILE, SET_UPLOADED_FILES, ADD_UPLOADED_FILE };
